### ISSUE TITLE
Checkpoint 1 - Instructor Notes

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [zcmarcus/CuriousCatBehavior#1]
What a fun project idea! I have a feeling this will be one of everyone's favorite demos at the end of the semester - who doesn't enjoy kitty videos?!

Problem statement does a good job explaining the project purpose. User stories hit the mark for the project objectives and seem be well-sized for a semester-long project. Nice job keeping up with your time log/reflection.

- [x] It looks like there is an option for "forgot password" on the screen design. Add a user story for this? Could be a stretch goal.  Could also provide an easy api integration if others do not pan out (javamail api for sending a password reset link or hint?)
- [x] Good start on the project plan - keep going!
- [x] Screens and reflection reference a login option with facebook and/or google - stretch goal? User story for this?

**Comment by zcmarcus** [comment]
I have updated user stories accordingly, making sure to reference intended MVP features vs. stretch goals.
