### ISSUE TITLE
Instructor Feedback - Week 5 Hibernate one-to-many

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [zcmarcus/CuriousCatBehavior#3]
Nice work with the one-to-many and implementing the generic dao!

- [x] I think you should be able to remove the entity-specific daos now and rely only on the generic?
- [x] Two additional cases to test for with the one to many. If a user has a role, what should happen when the role is deleted? Should the user stick around? Does it?   Then, if a user is deleted, should all associated roles be deleted? Are they?

**Comment by zcmarcus** [comment]
I've removed all DAOs other than Generic, and I have added tests for both of these cases. However, I'm not totally satisfied with the current behavior if I delete a user role (child table). For example, if a user has one role ('user'), and I am able to delete that role, thus leaving the user role-less, I think that is going to cause issues. What I'd like to do is set up something like a trigger (is that the right term?) to default a user's role to 'user' if all existing roles are deleted, but the user still exists. Still pondering it...
